apiVersion: v2
name: keycloak-client-operator
description: Kubernetes Operator for managing Keycloak Clients via CRD
type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - keycloak
  - iam
  - operator
  - kubernetes

maintainers:
  - name: BWI Team

sources:
  - https://github.com/bwi/keycloak-solution
