{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keycloak-client-operator.serviceAccountName" . }}
  labels:
    {{- include "keycloak-client-operator.labels" . | nindent 4 }}
{{- end }}
